name: UniversalVocoding
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.9.30
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - conda=4.10.3
  - conda-package-handling=1.7.3
  - cryptography=3.4.8
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.2
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - ninja=1.10.2
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.2.4
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.9.7
  - pytorch=1.9.1
  - readline=8.1
  - requests=2.26.0
  - ruamel_yaml=0.15.100
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - tqdm=4.62.2
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.7
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - audioread==2.1.9
    - decorator==5.1.0
    - importlib-resources==5.2.2
    - joblib==1.1.0
    - librosa==0.8.1
    - llvmlite==0.37.0
    - numba==0.54.1
    - numpy==1.20.3
    - omegaconf==2.1.1
    - packaging==21.0
    - pooch==1.5.2
    - pyparsing==2.4.7
    - pyyaml==6.0
    - resampy==0.2.2
    - scikit-learn==1.0
    - scipy==1.7.1
    - soundfile==0.10.3.post1
    - threadpoolctl==3.0.0
    - univoc==0.2.1
    - zipp==3.6.0
